swiftmailer:
   # url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: gmail
    auth_mode: login
    encryption: ssl
    port: 465
    host: smtp.gmail.com
    username: romleb2002@gmail.com
    password:
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
